/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsteroidsRouteImport } from './routes/asteroids'
import { Route as BreakoutRouteImport } from './routes/breakout'
import { Route as CatchRouteImport } from './routes/catch'
import { Route as CodebreakerRouteImport } from './routes/codebreaker'
import { Route as DungeonRouteImport } from './routes/dungeon'
import { Route as FroggerRouteImport } from './routes/frogger'
import { Route as InvadersRouteImport } from './routes/invaders'
import { Route as LanderRouteImport } from './routes/lander'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MinesweeperRouteImport } from './routes/minesweeper'
import { Route as MissileRouteImport } from './routes/missile'
import { Route as MoleRouteImport } from './routes/mole'
import { Route as PongRouteImport } from './routes/pong'
import { Route as RaceRouteImport } from './routes/race'
import { Route as ReactionRouteImport } from './routes/reaction'
import { Route as SimonRouteImport } from './routes/simon'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as SnakeRouteImport } from './routes/snake'
import { Route as TictactoeRouteImport } from './routes/tictactoe'
import { Route as TypingRouteImport } from './routes/typing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsteroidsRoute = AsteroidsRouteImport.update({
  id: '/asteroids',
  path: '/asteroids',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakoutRoute = BreakoutRouteImport.update({
  id: '/breakout',
  path: '/breakout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatchRoute = CatchRouteImport.update({
  id: '/catch',
  path: '/catch',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebreakerRoute = CodebreakerRouteImport.update({
  id: '/codebreaker',
  path: '/codebreaker',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonRoute = DungeonRouteImport.update({
  id: '/dungeon',
  path: '/dungeon',
  getParentRoute: () => rootRouteImport,
} as any)
const FroggerRoute = FroggerRouteImport.update({
  id: '/frogger',
  path: '/frogger',
  getParentRoute: () => rootRouteImport,
} as any)
const InvadersRoute = InvadersRouteImport.update({
  id: '/invaders',
  path: '/invaders',
  getParentRoute: () => rootRouteImport,
} as any)
const LanderRoute = LanderRouteImport.update({
  id: '/lander',
  path: '/lander',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MinesweeperRoute = MinesweeperRouteImport.update({
  id: '/minesweeper',
  path: '/minesweeper',
  getParentRoute: () => rootRouteImport,
} as any)
const MissileRoute = MissileRouteImport.update({
  id: '/missile',
  path: '/missile',
  getParentRoute: () => rootRouteImport,
} as any)
const MoleRoute = MoleRouteImport.update({
  id: '/mole',
  path: '/mole',
  getParentRoute: () => rootRouteImport,
} as any)
const PongRoute = PongRouteImport.update({
  id: '/pong',
  path: '/pong',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactionRoute = ReactionRouteImport.update({
  id: '/reaction',
  path: '/reaction',
  getParentRoute: () => rootRouteImport,
} as any)
const SimonRoute = SimonRouteImport.update({
  id: '/simon',
  path: '/simon',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const SnakeRoute = SnakeRouteImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => rootRouteImport,
} as any)
const TictactoeRoute = TictactoeRouteImport.update({
  id: '/tictactoe',
  path: '/tictactoe',
  getParentRoute: () => rootRouteImport,
} as any)
const TypingRoute = TypingRouteImport.update({
  id: '/typing',
  path: '/typing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asteroids': typeof AsteroidsRoute
  '/breakout': typeof BreakoutRoute
  '/catch': typeof CatchRoute
  '/codebreaker': typeof CodebreakerRoute
  '/dungeon': typeof DungeonRoute
  '/frogger': typeof FroggerRoute
  '/invaders': typeof InvadersRoute
  '/lander': typeof LanderRoute
  '/memory': typeof MemoryRoute
  '/minesweeper': typeof MinesweeperRoute
  '/missile': typeof MissileRoute
  '/mole': typeof MoleRoute
  '/pong': typeof PongRoute
  '/race': typeof RaceRoute
  '/reaction': typeof ReactionRoute
  '/simon': typeof SimonRoute
  '/slots': typeof SlotsRoute
  '/snake': typeof SnakeRoute
  '/tictactoe': typeof TictactoeRoute
  '/typing': typeof TypingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asteroids': typeof AsteroidsRoute
  '/breakout': typeof BreakoutRoute
  '/catch': typeof CatchRoute
  '/codebreaker': typeof CodebreakerRoute
  '/dungeon': typeof DungeonRoute
  '/frogger': typeof FroggerRoute
  '/invaders': typeof InvadersRoute
  '/lander': typeof LanderRoute
  '/memory': typeof MemoryRoute
  '/minesweeper': typeof MinesweeperRoute
  '/missile': typeof MissileRoute
  '/mole': typeof MoleRoute
  '/pong': typeof PongRoute
  '/race': typeof RaceRoute
  '/reaction': typeof ReactionRoute
  '/simon': typeof SimonRoute
  '/slots': typeof SlotsRoute
  '/snake': typeof SnakeRoute
  '/tictactoe': typeof TictactoeRoute
  '/typing': typeof TypingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asteroids': typeof AsteroidsRoute
  '/breakout': typeof BreakoutRoute
  '/catch': typeof CatchRoute
  '/codebreaker': typeof CodebreakerRoute
  '/dungeon': typeof DungeonRoute
  '/frogger': typeof FroggerRoute
  '/invaders': typeof InvadersRoute
  '/lander': typeof LanderRoute
  '/memory': typeof MemoryRoute
  '/minesweeper': typeof MinesweeperRoute
  '/missile': typeof MissileRoute
  '/mole': typeof MoleRoute
  '/pong': typeof PongRoute
  '/race': typeof RaceRoute
  '/reaction': typeof ReactionRoute
  '/simon': typeof SimonRoute
  '/slots': typeof SlotsRoute
  '/snake': typeof SnakeRoute
  '/tictactoe': typeof TictactoeRoute
  '/typing': typeof TypingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asteroids'
    | '/breakout'
    | '/catch'
    | '/codebreaker'
    | '/dungeon'
    | '/frogger'
    | '/invaders'
    | '/lander'
    | '/memory'
    | '/minesweeper'
    | '/missile'
    | '/mole'
    | '/pong'
    | '/race'
    | '/reaction'
    | '/simon'
    | '/slots'
    | '/snake'
    | '/tictactoe'
    | '/typing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asteroids'
    | '/breakout'
    | '/catch'
    | '/codebreaker'
    | '/dungeon'
    | '/frogger'
    | '/invaders'
    | '/lander'
    | '/memory'
    | '/minesweeper'
    | '/missile'
    | '/mole'
    | '/pong'
    | '/race'
    | '/reaction'
    | '/simon'
    | '/slots'
    | '/snake'
    | '/tictactoe'
    | '/typing'
  id:
    | '__root__'
    | '/'
    | '/asteroids'
    | '/breakout'
    | '/catch'
    | '/codebreaker'
    | '/dungeon'
    | '/frogger'
    | '/invaders'
    | '/lander'
    | '/memory'
    | '/minesweeper'
    | '/missile'
    | '/mole'
    | '/pong'
    | '/race'
    | '/reaction'
    | '/simon'
    | '/slots'
    | '/snake'
    | '/tictactoe'
    | '/typing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsteroidsRoute: typeof AsteroidsRoute
  BreakoutRoute: typeof BreakoutRoute
  CatchRoute: typeof CatchRoute
  CodebreakerRoute: typeof CodebreakerRoute
  DungeonRoute: typeof DungeonRoute
  FroggerRoute: typeof FroggerRoute
  InvadersRoute: typeof InvadersRoute
  LanderRoute: typeof LanderRoute
  MemoryRoute: typeof MemoryRoute
  MinesweeperRoute: typeof MinesweeperRoute
  MissileRoute: typeof MissileRoute
  MoleRoute: typeof MoleRoute
  PongRoute: typeof PongRoute
  RaceRoute: typeof RaceRoute
  ReactionRoute: typeof ReactionRoute
  SimonRoute: typeof SimonRoute
  SlotsRoute: typeof SlotsRoute
  SnakeRoute: typeof SnakeRoute
  TictactoeRoute: typeof TictactoeRoute
  TypingRoute: typeof TypingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asteroids': {
      id: '/asteroids'
      path: '/asteroids'
      fullPath: '/asteroids'
      preLoaderRoute: typeof AsteroidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakout': {
      id: '/breakout'
      path: '/breakout'
      fullPath: '/breakout'
      preLoaderRoute: typeof BreakoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catch': {
      id: '/catch'
      path: '/catch'
      fullPath: '/catch'
      preLoaderRoute: typeof CatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebreaker': {
      id: '/codebreaker'
      path: '/codebreaker'
      fullPath: '/codebreaker'
      preLoaderRoute: typeof CodebreakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeon': {
      id: '/dungeon'
      path: '/dungeon'
      fullPath: '/dungeon'
      preLoaderRoute: typeof DungeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frogger': {
      id: '/frogger'
      path: '/frogger'
      fullPath: '/frogger'
      preLoaderRoute: typeof FroggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invaders': {
      id: '/invaders'
      path: '/invaders'
      fullPath: '/invaders'
      preLoaderRoute: typeof InvadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lander': {
      id: '/lander'
      path: '/lander'
      fullPath: '/lander'
      preLoaderRoute: typeof LanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minesweeper': {
      id: '/minesweeper'
      path: '/minesweeper'
      fullPath: '/minesweeper'
      preLoaderRoute: typeof MinesweeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missile': {
      id: '/missile'
      path: '/missile'
      fullPath: '/missile'
      preLoaderRoute: typeof MissileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mole': {
      id: '/mole'
      path: '/mole'
      fullPath: '/mole'
      preLoaderRoute: typeof MoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pong': {
      id: '/pong'
      path: '/pong'
      fullPath: '/pong'
      preLoaderRoute: typeof PongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reaction': {
      id: '/reaction'
      path: '/reaction'
      fullPath: '/reaction'
      preLoaderRoute: typeof ReactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simon': {
      id: '/simon'
      path: '/simon'
      fullPath: '/simon'
      preLoaderRoute: typeof SimonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snake': {
      id: '/snake'
      path: '/snake'
      fullPath: '/snake'
      preLoaderRoute: typeof SnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tictactoe': {
      id: '/tictactoe'
      path: '/tictactoe'
      fullPath: '/tictactoe'
      preLoaderRoute: typeof TictactoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typing': {
      id: '/typing'
      path: '/typing'
      fullPath: '/typing'
      preLoaderRoute: typeof TypingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsteroidsRoute: AsteroidsRoute,
  BreakoutRoute: BreakoutRoute,
  CatchRoute: CatchRoute,
  CodebreakerRoute: CodebreakerRoute,
  DungeonRoute: DungeonRoute,
  FroggerRoute: FroggerRoute,
  InvadersRoute: InvadersRoute,
  LanderRoute: LanderRoute,
  MemoryRoute: MemoryRoute,
  MinesweeperRoute: MinesweeperRoute,
  MissileRoute: MissileRoute,
  MoleRoute: MoleRoute,
  PongRoute: PongRoute,
  RaceRoute: RaceRoute,
  ReactionRoute: ReactionRoute,
  SimonRoute: SimonRoute,
  SlotsRoute: SlotsRoute,
  SnakeRoute: SnakeRoute,
  TictactoeRoute: TictactoeRoute,
  TypingRoute: TypingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
